### ISSUE TITLE
System enters IR remote learning mode if powered up when sensors are in sunlight

### ISSUE THREAD

**Issue by MrMap** [FPV-Combat/Main_board_v2#10]
Quite often, when system is powered up while in sunlight conditions, the combat system enters IR remote control learning mode.
Workaround can be to shield the sensors with hand or re-power in shadow. This should not be neccesary.

How about another criteria for entering the remote setup mode, like trigger channel active (shooting) while powering up? 
This would avoid being tricked by IR sensor ghosts.

Or some other criteria achieving the same objective, avoiding false cue for IR setup mode.

**Comment by ysoldak** [comment]
In upcoming FW 2.6.0, we changed the way we navigate menu. No need IR remote anymore.

But you have to configure a special function or a mixer in your radio to send `1700us` on momentary switch press. In addition to already existing trigger that sends >`1850us`.

This way we have two real and four "virtual" buttons (can distinguish short and long presses for each physical button).
These four actions are enough to be able to control settings menu.

So this is no-issue anymore in upcoming 2.6.0 release.
Closing.
