### ISSUE TITLE
HW: 2.6 SW: FPVC 2.6.0-b4(also-b6) - OSD on Digital is off center and out of image at startup 

### ISSUE THREAD

**Issue by chaos5235** [FPV-Combat/Main_board_v2#14]
HW: 2.6 SW: FPVC 2.6.0-b4 - OSD on Digital is off center and out of image at startup

Also in: HW: 2.6 SW: FPVC 2.6.0-b6

**Comment by chaos5235** [comment]
fixed in FPVC 2.6.0-B7

**Comment by ysoldak** [comment]
An attempt to fix this resulted in #20
But closing this, since not a problem anymore. "Fixed" in 2.6.0-B8.
