### ISSUE TITLE
Option to disable Crosshair

### ISSUE THREAD

**Issue by chaos5235** [FPV-Combat/Main_board_v2#16]
As a user I want to have the option to choose from the different Crosshairs also an empty one.

So I want an empty crossair even when the FPVC-Font is enabled

**Comment by ysoldak** [comment]
Good idea!

**Comment by ysoldak** [comment]
Implemented in 2.6.0-B14

**Comment by ysoldak** [comment]
@chaos5235 please confirm and close if fixed

**Comment by chaos5235** [comment]
Confirmed, successfully implemented
