### ISSUE TITLE
Broken crosshair icons preview

### ISSUE THREAD

**Issue by chaos5235** [FPV-Combat/Main_board_v2#18]
As a user i want to see a small preview of the crosshair in the interface setup in b8 i saw some artifacts when i switched through the crosshairs like it was pointing to somewhere on the charmap

**Comment by ysoldak** [comment]
Hm, strange, was working for me as expected last time I tried, need to test more.
I assume that was DJI V1 hacked with WTFOS and custom font loaded.

Thanks for the report!

**Comment by chaos5235** [comment]
Yes IT was with dji v1 wtfos and the custom Fonts you shared

**Comment by ysoldak** [comment]
Please try with 2.6.0-B11 and latest WTFOS fonts I gave you

**Comment by ysoldak** [comment]
@chaos5235 Is this still problem with Beat11?

**Comment by chaos5235** [comment]
fixed
