### ISSUE TITLE
Rename 3 items in battle menu

### ISSUE THREAD

**Issue by chaos5235** [FPV-Combat/Main_board_v2#19]
In Battle Menue it would be nicer to have.

Friendly fire instead of Friend Fire
Shooting Power instead of shoot power
Shooting Rate instead of shoot Rate

Maybe Armor is better then defense as wording - because defense is more something that shoots back than what is meant here

**Comment by ysoldak** [comment]
Need to check if we have enough space for that in Analog OSD.

**Comment by ysoldak** [comment]
"Friendly Fire" fixed in 2.6.0-b15, rest is left the same due to lack of space.
Defense/Armor can decide later.
