### ISSUE TITLE
Bigger Pads and Holes for Power Connection

### ISSUE THREAD

**Issue by chaos5235** [FPV-Combat/Main_board_v2#22]
The actual Holes and solder area for Supply Voltage is pretty small  no normal power cable can be pushed through the holes.

It would be great to have an additional big solder pad to enable users to use a descent power connection cable alternativly to servo connector pins

 
![Screenshot 2024-01-18 113156](https://github.com/FPV-Combat/Main_board_v2/assets/95625836/58d75d0a-1fea-4a03-93c8-065e138c73cf)

**Comment by ioteo** [comment]
@chaos5235 so pads without holes or those pads in addition to the existing ones? Since there is not really much space there...
![Screenshot 2024-02-20 144611](https://github.com/FPV-Combat/Main_board_v2/assets/29753593/64610c61-feb1-45fd-9355-18c0f1634162)

**Comment by chaos5235** [comment]
maybe just 2 bigger holes instad of 2 small ones....

**Comment by ioteo** [comment]
Completed with V2.6_r0.5, maximized pad's size and increased also holes diameter to 1.5mm without changing the shape or position maintaining same pitch as the rest of the board (2.54mm).
