### ISSUE TITLE
HW:2.6 - SW- B8 - LEDs - Only Ammo and Team LEDs are shown - LIVE LEDs are missing

### ISSUE THREAD

**Issue by chaos5235** [FPV-Combat/Main_board_v2#26]
HW:2.6 - SW- B8 - LEDs - Only Ammo and Team LEDs are shown - LIVE LEDs are missing - also after factory reset

tried with different values - all with same effect - no leds for Lives - only ammo and team on all tried settings

**Comment by chaos5235** [comment]
seems to be related to faulty RGB strip or wrong type of LEDs

**Comment by ysoldak** [comment]
Closing due to led strip problem. Other strips work.
