### ISSUE TITLE
Important - move Ammo and Lifes up a bit in image to avoid conflict with default DJI Values

### ISSUE THREAD

**Issue by chaos5235** [FPV-Combat/Main_board_v2#37]
Please move up Ammo and Life Icons and amount to avoid overlapping with bandwidth display of DJI Default display

**Comment by ysoldak** [comment]
Which version you observed this on? Released 2.6.0?
If so, please try latest 2.6.1 beta, shall be fixed there...

**Comment by ysoldak** [comment]
Fixed in 2.6.1
