### ISSUE TITLE
Increase voltage reading speed

### ISSUE THREAD

**Issue by ioteo** [FPV-Combat/Main_board_v2#39]
Since main loop's speed has been reduced need to improve battery voltage reading by lowering averaging samples or increasing the analog sample's rate.
The effect is mainly visible at start-up since the voltage reading takes several seconds to reach the actual value.
This is extremely useful to clearly see faulty batteries by monitoring voltage sag at higher currents.

**Comment by ysoldak** [comment]
Fixed in 2.6.1
