### ISSUE TITLE
ISSUE: you can get "damage" beeing in the setup menue"

### ISSUE THREAD

**Issue by chaos5235** [FPV-Combat/Main_board_v2#7]
To Reproduce:
- shoot ready
- go to setup menue ( i liked that this was blocked before)  [before it was not possible to enter setup menue when you already shot ready]
- in the middle of setting stuff up sometimes "heavy damage" 

Software Version 2.5-C476AD0E

**Comment by ysoldak** [comment]
Fixed in upcoming 2.6.0 -- we now have different menu in "battle" mode. Plus, we don't use IR remote to navigate the menu anymore anyway.
